name: cygnet
favicon: null
layout_spectrum: 0.50036
typography_spectrum: 0.127467
title: 'cygnet.online | all the things in Cygnet, Tasmania'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-59862159-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a08'
    - '#3e404c'
    - '#f9fffb'
    - '#918b8b'
    - '#cadad0'
  brandStrength: 0.017269
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
