name: cygnet
favicon: null
layout_spectrum: 1
typography_spectrum: 0.127467
title: cygnet.online
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a08'
    - '#3e404c'
    - '#f9fffb'
    - '#918b8b'
    - '#cadad0'
  brandStrength: 0.125
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.80921
purpose:
  - name: null
    item: null
    url: null
